language: bash
sudo: required
dist: trusty

before_install:
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
    - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
    - sudo apt-get update
    - sudo apt-get install -y ros-indigo-ros-base
    - echo "source /opt/ros/indigo/setup.bash" >> ~/.bashrc
    - source ~/.bashrc
    - sudo rosdep init
    - rosdep update

install:
    - mkdir -p ~/catkin_ws/src
    - cd ~/catkin_ws
    - catkin_make
    - source devel/setup.bash

before_script:
    - cd ~/catkin_ws/src

script:
    - git clone https://github.com/baalexander/rospy_message_converter
    - git clone https://github.com/canopy-ros/canopy_client
    - cd canopy_client
    - source canopy_client_install.sh